##
## EPITECH PROJECT, 2023
## B-YEP-400-BER-4-1-zappy-matthis.brocheton
## File description:
## Makefile
##

all: zappy_ai

zappy_ai: zappy_ai.py
	cp zappy_ai.py zappy_ai
	chmod +x zappy_ai

clean:
	rm -rf __pycache__ *.pyc

fclean: clean
	rm -f zappy_ai

re: fclean all
